# Generated by Django 4.2.5 on 2023-10-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstructField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=150)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=150)),
                ('template', models.FileField(upload_to='uploads/templates/')),
                ('fields_info', models.JSONField(blank=True, null=True)),
                ('fields', models.ManyToManyField(related_name='abs_field', to='main.abstructfield')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.documenttype')),
            ],
        ),
    ]
