# Generated by Django 4.2.5 on 2023-10-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='fields',
            new_name='fields1',
        ),
    ]
