# Generated by Django 4.2.5 on 2023-10-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_abstructfield_cost_abstructfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstructfield',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rendered_template',
            field=models.FileField(default=1, upload_to='uploads/rendered/'),
            preserve_default=False,
        ),
    ]
